name: linguadash
description: "A modern language learning game."
publish_to: 'none'
version: 1.0.0+3

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_mobile_ads: ^5.1.0
  # State Management
  provider: ^6.1.1
  
  # Utilities
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  path_provider: ^2.1.2
  url_launcher: ^6.2.5 # Mail atmak iÃ§in gerekli
  
  # Media
  audioplayers: ^5.2.1
  
  # UI & Animation
  flutter_animate: ^4.5.0
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/data/
    - assets/sounds/
    - assets/icons/
  fonts:
    - family: Monogram
      fonts:
        - asset: assets/fonts/monogram-extended.ttf

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"
  min_sdk_android: 21